source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSURLSession-Mock_Example' do
  pod "NSURLSession-Mock", :path => "../"
  
  target 'NSURLSession-Mock_Tests' do
      inherit! :search_paths
      
      pod "AFNetworking", "~> 3.0"
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
