source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSURLSession-Mock_Example' do
  pod 'NSURLSession-Mock', :path => '../'
  
  target 'NSURLSession-Mock_Tests' do
      inherit! :search_paths
      
      pod 'AFNetworking'
      pod 'Alamofire'
  end
end
